### ISSUE TITLE
remote-test.sh -u option negates utility of if/then check for AXIS_DEVICE_IP

### ISSUE THREAD

**Issue by JsGjKJzi** [AxisCommunications/acap-rs#165]
### Describe the bug
https://github.com/AxisCommunications/acap-rs/blob/4224cf48b836ef297c586469b5fc6d6158ceca5e/bin/remote-test.sh#L1-L4
By setting the -u option for bash, unset variables are treated as errors during parameter expansion. That means if `AXIS_DEVICE_IP` is not set, the script will exit with an error: 
`/workspaces/acap-rs/bin/remote-test.sh: 4: AXIS_DEVICE_IP: parameter not set`

This is because the `if [ -n "${AXIS_DEVICE_IP}" ]` actually has to expand the variable to see if the value is non-zero.

### To reproduce

1. Set up a new environment in the default dev container
2. Add remote-test.sh to path via `export PATH=$PATH:/workspaces/acap-rs/bin`
3. Run `cargo test --tests -p acap-vapix -- --nocapture`
4. See error `/workspaces/acap-rs/bin/remote-test.sh: 4: AXIS_DEVICE_IP: parameter not set`

### Environment

- Default devcontainer environment

### Possible fixes
Bash added the -v conditional comparison operator which checks for the existence of a variable and was introduced to work in concert with `set -u` [^1]

So, this is a working fix but requires the use of `bash` instead of plain `sh`:
```
#!/bin/bash
set -eu

if [ -v AXIS_DEVICE_IP ]; then
    LOCAL_PATH="$1"
    shift

    REMOTE_PATH=/tmp/`basename $LOCAL_PATH`
    CARGO_TEST_CAMERA=${AXIS_DEVICE_USER:-root}@${AXIS_DEVICE_IP}
    scp -p "$LOCAL_PATH" $CARGO_TEST_CAMERA:$REMOTE_PATH
    ssh $CARGO_TEST_CAMERA ${REMOTE_ENV:-} $REMOTE_PATH "$@"
else
    $@
fi
```

[^1]: [https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html](https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html)

**Comment by apljungquist** [comment]
I do like a thorough bug report, but you don't need to do that for my sake if you immediately fix the issue yourself :grin:.

**Comment by JsGjKJzi** [comment]
From within a dev container (I use VSCode) the following commands should trigger the error.
```bash
unset AXIS_DEVICE_IP
cargo test --tests -p acap-vapix --target aarch64-unknown-linux-gnu -- --nocapture 
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.37s
     Running unittests src/lib.rs (target/aarch64-unknown-linux-gnu/debug/deps/acap_vapix-491c00f9bfd3952d)
/workspaces/acap-rs/bin/remote-test.sh: 9: AXIS_DEVICE_IP: parameter not set
```
